name: test

on: [push, pull_request]

env:
  npm_config_cache: /tmp/npm-cache

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - id: cache-npm
      name: restore npm cache
      uses: actions/cache@v3
      with:
        key: npm-cache-${{ github.ref_name }}
        path: ${{ env.npm_config_cache }}
    - run: npm install

    - run: npm run lint
    - run: npm run test-unit

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - id: cache-npm
      name: restore npm cache
      uses: actions/cache@v3
      with:
        key: npm-cache-${{ github.ref_name }}
        path: ${{ env.npm_config_cache }}
    - run: npm install

    - run: npm run lint
    - run: npm run test-integration

  e2e-tests:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - id: cache-npm
      name: restore npm cache
      uses: actions/cache@v3
      with:
        key: npm-cache-${{ github.ref_name }}
        path: ${{ env.npm_config_cache }}
    - run: npm install

    - run: npm run lint
    - run: npm run test-e2e
